-- Candidates
MERGE INTO CANDIDATE (ID, NAME, EMAIL)
KEY (ID)
VALUES (1, 'Aishwarya', 'aishu@test.com');

MERGE INTO CANDIDATE (ID, NAME, EMAIL)
KEY (ID)
VALUES (2, 'Rahul', 'rahul@test.com');

-- Interviewers
MERGE INTO INTERVIEWER (ID, NAME, EXPERTISE)
KEY (ID)
VALUES (1, 'John', 'Java');

MERGE INTO INTERVIEWER (ID, NAME, EXPERTISE)
KEY (ID)
VALUES (2, 'Mary', 'Spring Boot');

MERGE INTO INTERVIEWER (ID, NAME, EXPERTISE)
KEY (ID)
VALUES (3, 'Alex', 'System Design');

-- Reset identity columns
ALTER TABLE CANDIDATE ALTER COLUMN ID RESTART WITH 100;
ALTER TABLE INTERVIEWER ALTER COLUMN ID RESTART WITH 100;
